name: rag-pipeline
channels:
  - defaults
dependencies:
  - python=3.12.12
  - langchain=1.0.3
  - langchain-core==1.0.2
  - langchain-classic==1.0.0
  - langchain-community==0.4.1
  - langchain-google-genai==3.0.1
  - langchain-mongodb==0.7.1
  - langchain-text-splitters==1.0.0
  - openai=1.50.1
  - pymongo=4.10.1
  - python-dotenv=1.0.1
  - jupyter